name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpython3-dev build-essential git-core libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
        # 自动接受 Google SDK 许可并安装必要的 build-tools
        yes | sudo $ANDROID_HOME/tools/bin/sdkmanager "build-tools;30.0.3" "platforms;android-30"

    - name: Build APK with Buildozer
      run: buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
      name: my-kivy-app-apk
      path: bin/*.apk
